/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.projetointegrador.gti.m.senac.go;

/**
 *
 * @author User
 */

import bin.projetointegrador.gti.m.senac.go.FileDir;
import bin.projetointegrador.gti.m.senac.go.FileHandle;
import entidade.projetointegrador.gti.m.senac.go.LineLog;
import entidade.projetointegrador.gti.m.senac.go.LogsAcess;
import java.util.ArrayList;

public class JFramePrimcipal extends javax.swing.JFrame {
    
    private FileDir fileOpen = new FileDir();
    private String setLocation;
    private FileHandle leitorArquivo = new FileHandle();
    
    
    /**
     * Creates new form JFramePrimcipal
     */
    public JFramePrimcipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedAcessos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAcessos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstatisticos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuFechar = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(683, 384));
        setName("Analizar Logs"); // NOI18N
        setPreferredSize(new java.awt.Dimension(384, 683));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados Estatísticos"));
        jPanel1.setName("Lista de Hosts "); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 580));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jTableAcessos.setAutoCreateRowSorter(true);
        jTableAcessos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableAcessos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Host", "Frequênica", "Porcentagem"
            }
        ));
        jTableAcessos.setEditingColumn(0);
        jTableAcessos.setEditingRow(0);
        jTableAcessos.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane2.setViewportView(jTableAcessos);

        jPanel1.add(jScrollPane2);

        jPanel2.setPreferredSize(new java.awt.Dimension(70, 235));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jTableEstatisticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cálculo", "Resultado"
            }
        ));
        jTableEstatisticos.setMinimumSize(new java.awt.Dimension(60, 60));
        jScrollPane1.setViewportView(jTableEstatisticos);

        jPanel2.add(jScrollPane1);

        jPanel1.add(jPanel2);

        jTabbedAcessos.addTab("Tabela de Acessos", jPanel1);

        getContentPane().add(jTabbedAcessos, "Acesos");
        jTabbedAcessos.getAccessibleContext().setAccessibleName("jTableAcessos");

        jMenuArquivo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuArquivo.setText("File");
        jMenuArquivo.setMinimumSize(new java.awt.Dimension(400, 400));

        jMenuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuAbrir);

        jMenuFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuFechar.setText("Fechar");
        jMenuFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFecharActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuFechar);

        jMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuSair);

        jMenuBar1.add(jMenuArquivo);
        jMenuArquivo.getAccessibleContext().setAccessibleName("Arquivo");

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFecharActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
         System.exit(1);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
            // TODO add your handling code here:
        
    
            //this.fileOpen
        this.setLocation = fileOpen.search();
        this.leitorArquivo.setPathFile(setLocation);
        this.leitorArquivo.readFile("\\|");
        
        LogsAcess log = new LogsAcess();
        LineLog line = new LineLog();
        log = this.leitorArquivo.controle.getLogs();
        ArrayList<LineLog> linesLogs = new ArrayList();
        linesLogs = log.getLine();
        System.out.print("xz");
        
        for(int xz = 0; xz < linesLogs.size(); xz++ )
        {
            System.out.print(linesLogs.get(xz).getTimestap().getDataStamp()+"\n");
            System.out.print(linesLogs.get(xz).getTimestap().getTimeStamp()+"\n");
            //System.out.print(log.getLine().get(xz));
        }
        
            
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrimcipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFechar;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedAcessos;
    private javax.swing.JTable jTableAcessos;
    private javax.swing.JTable jTableEstatisticos;
    // End of variables declaration//GEN-END:variables
}
